name: better_player
description: Advanced video player. It solves many typical use cases and it's easy to run.
version: 0.0.84
homepage: https://github.com/jhomlala/betterplayer
documentation: https://jhomlala.github.io/betterplayer/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  wakelock_plus: ^1.2.5
  meta: ^1.12.0
  flutter_widget_from_html_core: ^0.15.1
  visibility_detector: ^0.4.0+2
  path_provider: ^2.1.3
  collection: ^1.18.0
  xml: ^6.5.0

dev_dependencies:
  lint: ^2.3.0
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
# dependency_overrides:
#   better_player_web:
#     path: ../better_player_web

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.better_player
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: BetterPlayerPlugin
      web:
        default_package: better_player_web